from . import help
from . import start
from . import admin
from . import partner
from . import work
from . import teacher
from . import employee
from . import pupil
from . import echo
from . import confirm
